In [10]:
import numpy as np

In [11]:
y=np.arange(0,8)

In [12]:
y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
y=np.arange(0,9)

In [14]:
y = np.reshape (y,(3,3))

In [15]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
z=np.eye (N=6,M=6)

In [17]:
z

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])